
language: cpp

os: linux
dist: trusty
sudo: required
compiler: gcc
services: docker

cache: ccache

env:
  global:
    - DOCKER_OPTS="--rm -ti -v ${HOME}/.ccache:/root/.ccache -v ${TRAVIS_BUILD_DIR}:/build -w /build"
  matrix:
    # Intraday calculations enabled
    - DOCKER_IMAGE=lballabio/quantlib-devenv:xenial
      CONFIGURE_FLAGS="--disable-static --enable-intraday"
      CXXFLAGS="-O2 -Wall -Wno-unknown-pragmas -Werror"
    # Indexed coupons enabled
    - DOCKER_IMAGE=lballabio/quantlib-devenv:xenial
      CONFIGURE_FLAGS="--disable-static --enable-indexed-coupons"
      CXXFLAGS="-O2 -Wall -Wno-unknown-pragmas -Werror"
    # Negative rates disabled
    - DOCKER_IMAGE=lballabio/quantlib-devenv:xenial
      CONFIGURE_FLAGS="--disable-static --disable-negative-rates"
      CXXFLAGS="-O2 -Wall -Wno-unknown-pragmas -Werror"
    # Thread-safe observe enabled
    - DOCKER_IMAGE=lballabio/quantlib-devenv:xenial
      CONFIGURE_FLAGS="--disable-static --enable-thread-safe-observer-pattern"
      CXXFLAGS="-O2 -Wall -Wno-unknown-pragmas -Werror"

before_install:
  - docker pull ${DOCKER_IMAGE}

script:
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./autogen.sh
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./configure ${CONFIGURE_FLAGS} CXXFLAGS="${CXXFLAGS}"
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --zero-stats
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --max-size=2.5G
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --show-stats
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} make -j 2
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ccache --show-stats
  - docker run ${DOCKER_OPTS} ${DOCKER_IMAGE} ./test-suite/quantlib-test-suite --log_level=message -- --faster

